        $countries = array(     
               "DZ" => array("country" => "Algeria", "continent" => "Africa"),     
                  "AO" => array("country" => "Angola", "continent" => "Africa"),   
                   "BJ" => array("country" => "Benin", "continent" => "Africa"),     
                    "BW" => array("country" => "Botswana", "continent" => "Africa"),  
                   "BF" => array("country" => "Burkina Faso", "continent" => "Africa"), 
                   "BI" => array("country" => "Burundi", "continent" => "Africa"),  
                   "CM" => array("country" => "Cameroon", "continent" => "Africa"),   
                  "CV" => array("country" => "Cape Verde", "continent" => "Africa"),     
                  "CF" => array("country" => "Central African Republic", "continent" => "Africa"),
                  "TD" => array("country" => "Chad", "continent" => "Africa"),
                  "KM" => array("country" => "Comoros", "continent" => "Africa"),
                  "CG" => array("country" => "Congo", "continent" => "Africa"),
                  "CD" => array("country" => "The Democratic Republic of The Congo", "continent" => "Africa"),
                  "CI" => array("country" => "Cote D'ivoire", "continent" => "Africa"),
                  "DJ" => array("country" => "Djibouti", "continent" => "Africa"),
                  "EG" => array("country" => "Egypt", "continent" => "Africa"), 
                  "GQ" => array("country" => "Equatorial Guinea", "continent" => "Africa"),
                  "ER" => array("country" => "Eritrea", "continent" => "Africa"),
                  "ET" => array("country" => "Ethiopia", "continent" => "Africa"),
                  "GA" => array("country" => "Gabon", "continent" => "Africa"),
                  "GM" => array("country" => "Gambia", "continent" => "Africa"), 
                  "GH" => array("country" => "Ghana", "continent" => "Africa"),
                  "GN" => array("country" => "Guinea", "continent" => "Africa"),
                  "GW" => array("country" => "Guinea-bissau", "continent" => "Africa"),
                  "KE" => array("country" => "Kenya", "continent" => "Africa"),
                  "LS" => array("country" => "Lesotho", "continent" => "Africa"),
                  "LR" => array("country" => "Liberia", "continent" => "Africa"), 
                  "LY" => array("country" => "Libya", "continent" => "Africa"),
                  "MG" => array("country" => "Madagascar", "continent" => "Africa"),
                  "MW" => array("country" => "Malawi", "continent" => "Africa"),
                  "ML" => array("country" => "Mali", "continent" => "Africa"),
                  "MR" => array("country" => "Mauritania", "continent" => "Africa"),
                  "MU" => array("country" => "Mauritius", "continent" => "Africa"),
                  "YT" => array("country" => "Mayotte", "continent" => "Africa"),
                  "MA" => array("country" => "Morocco", "continent" => "Africa"),
                  "MZ" => array("country" => "Mozambique", "continent" => "Africa"), 
                  "NA" => array("country" => "Namibia", "continent" => "Africa"),    
                  "NE" => array("country" => "Niger", "continent" => "Africa"),   
                  "NG" => array("country" => "Nigeria", "continent" => "Africa"), 
                  "RE" => array("country" => "Reunion", "continent" => "Africa"), 
                  "RW" => array("country" => "Rwanda", "continent" => "Africa"),  
                  "SH" => array("country" => "Saint Helena", "continent" => "Africa"),    
                  "ST" => array("country" => "Sao Tome and Principe", "continent" => "Africa"),  
                  "SN" => array("country" => "Senegal", "continent" => "Africa"),    
                  "SC" => array("country" => "Seychelles", "continent" => "Africa"), 
                  "SL" => array("country" => "Sierra Leone", "continent" => "Africa"),
                  "SO" => array("country" => "Somalia", "continent" => "Africa"),
                  "ZA" => array("country" => "South Africa", "continent" => "Africa"),  
                  "SD" => array("country" => "Sudan", "continent" => "Africa"),     
                  "SZ" => array("country" => "Swaziland", "continent" => "Africa"), 
                  "TZ" => array("country" => "Tanzania, United Republic of", "continent" => "Africa"), 
                  "TG" => array("country" => "Togo", "continent" => "Africa"), 
                  "TN" => array("country" => "Tunisia", "continent" => "Africa"), 
                  "UG" => array("country" => "Uganda", "continent" => "Africa"),   
                  "EH" => array("country" => "Western Sahara", "continent" => "Africa"),
                  "ZM" => array("country" => "Zambia", "continent" => "Africa"),      
                   "ZW" => array("country" => "Zimbabwe", "continent" => "Africa")    );
